name: Deploy to Cloud Run (Source-based)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # ✅ Authenticate to Google Cloud
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    # ✅ Set up gcloud SDK
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: cvoapi

    # ✅ Deploy directly from source (no Docker build/push)
    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy meme-generator \
          --source . \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated \
          --set-env-vars "IMGFLIP_USERNAME=${{ secrets.IMGFLIP_USERNAME }},IMGFLIP_PASSWORD=${{ secrets.IMGFLIP_PASSWORD }},GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}"
