name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # ✅ Authenticate to Google Cloud
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    # ✅ Set up gcloud SDK
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: novi-464614

    # ✅ Configure Docker to push to Artifact Registry
    - name: Configure Docker authentication
      run: gcloud auth configure-docker us-central1-docker.pkg.dev

    # ✅ Build and push Docker image
    - name: Build and Push Docker Image
      run: |
        docker build -t us-central1-docker.pkg.dev/novi-464614/meme-generator-repo/meme-generator:latest .
        docker push us-central1-docker.pkg.dev/novi-464614/meme-generator-repo/meme-generator:latest

    # ✅ Deploy to Cloud Run
    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy meme-generator \
          --image us-central1-docker.pkg.dev/novi-464614/meme-generator-repo/meme-generator:latest \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated \
          --set-env-vars "IMGFLIP_USERNAME=${{ secrets.IMGFLIP_USERNAME }},IMGFLIP_PASSWORD=${{ secrets.IMGFLIP_PASSWORD }},GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}"
